<?php

namespace Tests\Feature;

use App\Models\Boats;
use App\Models\Booking;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class BookingTests extends TestCase
{

    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
        $this->user = User::factory()->create([
            'business_role' => 'company'
        ]);
    }

    /**
     * @test
     */
    public function it_shows_all_the_bookings_successfully(){

        Boats::factory(1)->create([
            'user_id' => $this->user->id
        ]);

        Booking::factory()->create([
            'number_of_adults' => 2,
            'total_price' => 80,
            'user_id' => $this->user->id
        ]);

        $response = $this->actingAs($this->user)->get('/booking');
        $response->assertStatus(200);
        $content = $response->getContent();
        $this->assertStringContainsString('2', $content);
        $this->assertStringContainsString('80', $content);
    }

    /**
     * @test
     */
    public function it_successfully_creates_a_booking_for_a_specific_boat()
    {
        //
    }

    /**
     * @test
     */
    public function it_successfully_prevents_overbooking_for_a_specific_departure_time_and_boat()
    {
        //
    }

    /**
     * @test
     */
    public function it_successfully_books_for_a_specific_departure_time()
    {
        //
    }

    /**
     * @test
     */
    public function it_successfully_updates_the_boat_capcity_for_a_specific_departure_time()
    {
        //
    }

}
